import React from 'react'
import { TabContent, TabPane, Nav, NavItem, NavLink, Card, Button, CardTitle, CardText, Row, Col } from 'reactstrap';
import classnames from 'classnames';

export default function ToppingsForm(props) {
  
    let {
        activeTab, 
        setActiveTab, 
        values,
        onInputChange,
        onSubmit,
        disabled,
        errors,
        onMeatsCheckboxChange,
        onVeggiesCheckboxChange
    } = props;

    const toggle = tab => {
      if(activeTab !== tab) setActiveTab(tab);
    }
  
    return (
      <div>
        <Nav tabs>
          <NavItem>
            <NavLink
              className={classnames({ active: activeTab === '1' })}
              onClick={() => { toggle('1'); }}
            >
              Meats
            </NavLink>
          </NavItem>
          <NavItem>
            <NavLink
              className={classnames({ active: activeTab === '2' })}
              onClick={() => { toggle('2'); }}
            >
              Veggies
            </NavLink>
          </NavItem>
        </Nav>
        <TabContent activeTab={activeTab}>
          <TabPane tabId="1">
            <Row>
                <label>pepperoni
                <input
                    type='checkbox'
                    name='pepperoni'
                    checked={values.toppings.meats.pepperoni}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>bacon
                <input
                    type='checkbox'
                    name='bacon'
                    checked={values.toppings.meats.bacon}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>chicken
                <input
                    type='checkbox'
                    name='chicken'
                    checked={values.toppings.meats.chicken}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>ham
                <input
                    type='checkbox'
                    name='ham'
                    checked={values.toppings.meats.ham}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>sausage
                <input
                    type='checkbox'
                    name='sausage'
                    checked={values.toppings.meats.sausage}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>Itialian sausage
                <input
                    type='checkbox'
                    name='itialian'
                    checked={values.toppings.meats.itialian}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>beef
                <input
                    type='checkbox'
                    name='beef'
                    checked={values.toppings.meats.beef}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>salami
                <input
                    type='checkbox'
                    name='salami'
                    checked={values.toppings.meats.salami}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>bbq chicken
                <input
                    type='checkbox'
                    name='bbqChicken'
                    checked={values.toppings.meats.bbqChicken}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>bbq brisket
                <input
                    type='checkbox'
                    name='bbqBrisket'
                    checked={values.toppings.meats.bbqBrisket}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>bbq pork
                <input
                    type='checkbox'
                    name='bbqPork'
                    checked={values.toppings.meats.bbqPork}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>bbq trio
                <input
                    type='checkbox'
                    name='bbqTrio'
                    checked={values.toppings.meats.bbqTrio}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>sliced meatballs
                <input
                    type='checkbox'
                    name='meatballs'
                    checked={values.toppings.meats.meatballs}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>sardines
                <input
                    type='checkbox'
                    name='sardines'
                    checked={values.toppings.meats.sardines}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>anchovies
                <input
                    type='checkbox'
                    name='anchovies'
                    checked={values.toppings.meats.anchovies}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>prawns
                <input
                    type='checkbox'
                    name='prawns'
                    checked={values.toppings.meats.prawns}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>capers
                <input
                    type='checkbox'
                    name='capers'
                    checked={values.toppings.meats.capers}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>tofu
                <input
                    type='checkbox'
                    name='tofu'
                    checked={values.toppings.meats.tofu}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>chorizo
                <input
                    type='checkbox'
                    name='chorizo'
                    checked={values.toppings.meats.chorizo}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>pastrami
                <input
                    type='checkbox'
                    name='pastrami'
                    checked={values.toppings.meats.pastrami}
                    onChange={onMeatsCheckboxChange}
                />
                </label>
            </Row>
          </TabPane>
          <TabPane tabId="2">
          <Row>
                <label>tomatoes
                <input
                    type='checkbox'
                    name='tomatoes'
                    checked={values.toppings.veggies.tomatoes}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>mushrooms
                <input
                    type='checkbox'
                    name='mushrooms'
                    checked={values.toppings.veggies.mushrooms}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>onions
                <input
                    type='checkbox'
                    name='onions'
                    checked={values.toppings.veggies.onions}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>black olives
                <input
                    type='checkbox'
                    name='blackOlives'
                    checked={values.toppings.veggies.blackOlives}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>green olives
                <input
                    type='checkbox'
                    name='greenOlives'
                    checked={values.toppings.veggies.greenOlives}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>green peppers
                <input
                    type='checkbox'
                    name='greenPeppers'
                    checked={values.toppings.veggies.greenPeppers}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>jalapenos
                <input
                    type='checkbox'
                    name='jalapenos'
                    checked={values.toppings.veggies.jalapenos}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>pineapple
                <input
                    type='checkbox'
                    name='pineapple'
                    checked={values.toppings.veggies.pineapple}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>basil
                <input
                    type='checkbox'
                    name='basil'
                    checked={values.toppings.veggies.basil}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>broccoli
                <input
                    type='checkbox'
                    name='broccoli'
                    checked={values.toppings.veggies.broccoli}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>chickpeas
                <input
                    type='checkbox'
                    name='chickpeas'
                    checked={values.toppings.veggies.chickpeas}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>artichoke hearts
                <input
                    type='checkbox'
                    name='artichoke'
                    checked={values.toppings.veggies.artichoke}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>spinach
                <input
                    type='checkbox'
                    name='spinach'
                    checked={values.toppings.veggies.spinach}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>bannana pepper
                <input
                    type='checkbox'
                    name='bannanaPepper'
                    checked={values.toppings.veggies.bannanaPepper}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>cauliflower
                <input
                    type='checkbox'
                    name='cauliflower'
                    checked={values.toppings.veggies.cauliflower}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>eggplant
                <input
                    type='checkbox'
                    name='eggplant'
                    checked={values.toppings.veggies.eggplant}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
            </Row>
            <Row>
                <label>Buffalo mozzerella
                <input
                    type='checkbox'
                    name='buffMoz'
                    checked={values.toppings.veggies.buffMoz}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>ricota
                <input
                    type='checkbox'
                    name='ricota'
                    checked={values.toppings.veggies.ricota}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>feta
                <input
                    type='checkbox'
                    name='feta'
                    checked={values.toppings.veggies.feta}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
                &nbsp;
                &nbsp;
                <label>goat cheese
                <input
                    type='checkbox'
                    name='goat'
                    checked={values.toppings.veggies.goat}
                    onChange={onVeggiesCheckboxChange}
                />
                </label>
            </Row>
          </TabPane>
        </TabContent>
      </div>
    );
}
